### ISSUE TITLE
🌟🐛🚀💬 [EPIC][Release][Bug] Nitro Bugfixes and Todos, pre Release 

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1230]
### List of Bugs

- [x] 🐛 Destroyed header #1554
- [x] 🐛 [Import] Comment dates are missing #1555
- [x] 🐛 Admin statistics error #1511
- [x] 🐛 Creating multiple comments on a post does not update the CommentList #1455
- [x] 🐛 Admin Dashboard page has all counters set to zero #1487
- [x] 🐛 Hashtags are imported with not allowed characters #1395
- [x] 🐛 A new post is added on the news feed page to the end of the loaded ones #1394
- [x] 🐛 Deleted Comment reappears after editing another #1391
- [x] 🐛 Only 6 posts of the 27 posts on my profile on the alpha are visible #1369
- [x] 🐛 Cannot edit post #1310
- [x] 🐛 ContributionForm CreatePost is throwing Vue errors #1311
- [x] 🐛 One cypress test fails but it does not fail the build #1312
- [x] 🐛 Cannot re-use existing hashtags #1315
- [x] 🐛 Scroll to comment via anchor link not working #1307
- [x] 🐛 Hashtag filter is broken #1308
- [x] 🐛 Hashtag links are not URL safe #1276
- [x] 🐛 On Firefox Comments `show less` in expanded view is often not clickable #1491
- [x] 🐛 TypeError: Cannot read property 'offsetTop' of null #1273
- [x] 🐛 Separate text at words #1219
- [x] 🐛 Post image: preview image differs from final result #1199
- [x] 🐛 Editor link button has no effect #1198
- [x] 🐛 Editor placeholder and menu overlap #1197
- [x] 🐛 Privacy policy, is different in German than in English #1189
- [x] 🐛 Follower count in floating window above user links does not increase #293
- [x] 🐛 Content Excerpt removes Linebreaks without replacing them with Spaces #858
- [x] 🐛 On news feed and user profile  the `↓ load more` button should disappear if there are no more posts to load #253 (maybe both is fixed by #845 ?)
- [x] 🐛 Admin pages statistics undefined error #1242
- [x] 🐛 Scroll to Posts Comment area doesn't work #1245
- [x] 🐛 Login design lack, have the Header items left and right aligned #1246
- [x] 🐛 Scroll to comment via anchor link not working #1307 
- [x] 🐛 Background is scrolling when overlay is open #1413 
- [x] 🐛 I see `notifications.menu.null` in notification list #1412 
- [ ] 🐛 On mobil the notification menu is not vanishing after clicking on it #1489 
- [x] 🐛 Moderator sees HTML in reported comments #1505
- [x] 🐛 Missing Translations for Tooltips on Article Categorie Icons #1502
- [x] 🐛 Missing Translation for new Post #1501

### List of Todos

- [x] 🚀 Update `lastActiveAt` on every JWT token check #1305

### List of Todos in Question (because of pre Release or in general)

- [x] 💬 Are Hashtags corrected at import to the possible chars?
- [x] 🐛 Bug statement of Usus08 #946
- [ ] 🐛 Responsive display problem #1172
- [x] 🚀 Footer has lacks of design #1206 
- [x] 🚀 @Username: Unique user identification if identical profile names exist #1069
- [x] 🚀 Reporting and Disabling should have a date-time and be sorted by #1247
- [ ] 💬 CSRF Protection? #1140
- [x] 🐛 Option from select input is not dynamic #1035 --> after release
- [x] 🐛 Profile Links in Posts visible after Profile Deletion #1506

**Comment by Tirokk** [comment]
@datenbrei I went through all the unchecked issues and checked them when they were already solved.
And like one can easily see we all did a really great job. 😍

The three still open ones I started a clarification process and put them on our `Roadmap`.

Because of that I take the freedom to close this.
Hope that’s for your sake.

**Comment by datenbrei** [comment]
Yes, hell, what a list! All the open issues are addressed elsewhere, so it's ok. This is also something we may need to change: That we write everything, that we do not these issues open just because of a bunch of things to do in the future.
