### ISSUE TITLE
Checklist ExpressJS Security Best Practices

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#203]
Implement basic security features: 
https://expressjs.com/en/advanced/best-practice-security.html

- [x] Don’t use deprecated or vulnerable versions of Express
- [x] Use TLS
- [x] Use Helmet
- [ ] Use cookies securely
- [ ] Prevent brute-force attacks against authorization
- [x] Ensure your dependencies are secure
- [ ] Avoid other known vulnerabilities
- [ ] Additional considerations

**Comment by Mastercuber** [comment]
Helmet is already in use. It's adding some headers to prevent clickjacking, Cross-Site-Scripting etc. See @appinteractive's link above, section helmet.

**Comment by appinteractive** [comment]
@Mastercuber it’s in use for the activity pub api but not for the GraphQL one.

**Comment by Mastercuber** [comment]
@appinteractive I added helmet in the ActivityPub Integration PR. 
[Here](https://github.com/Human-Connection/Human-Connection/blob/67cbd129a9d186e2f09d1894dc9fa2feef95f185/backend/src/server.js#L63) you can see that's in use for both. The GraphQL express server uses it and while the ActivtyPub Service is one express router and also get used by the GraphQL express server it is also used by both.

**Comment by roschaefer** [comment]
@Mastercuber alright cool! I fleshed out the issue description and check one of the todos.
