### ISSUE TITLE
:star2: [EPIC] Styleguide Migration

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#2074]
## :star2: EPIC – Styleguide Migration

We want to transition from relying on [Nitro Styleguide](https://github.com/Human-Connection/Nitro-Styleguide) to having all design tokens and components within our main repo. The following items need to be migrated:

### Design Tokens
- [ ] icons
- [ ] logos
- [ ] color: used ~ 52 times in 12 files
- [ ] text-color: used ~ 13 times in 8 files
- [ ] background-color: used ~ 20 times in 6 files
- [ ] border-color: used ~ 4 times in 3 files
- [ ] border-size: used ~ 6 times in 2 files
- [ ] border-radius: used ~ 10 times in 7 files
- [ ] font-size: used ~ 7 times in 5 files
- [ ] font-space: used ~ 1 times in 1 file
- [ ] font-family: used ~ 1 times in 1 file
- [x] font-weight: not used
- [x] line-height: not used
- [x] letter-spacing: not used
- [x] opacity: not used
- [ ] space: used ~ 63 times in 14 files
- [ ] size: used ~ 33 times in 2 files
- [ ] box-shadow: used ~ 7 times in 6 files
- [x] duration: not used
- [x] ease: not used
- [ ] z-index: used ~ 4 times in 4 files
- [x] media-query: not used

### Layout Components
- [ ] ds-card: used ~ 55 times in 43 files
- [ ] ds-container: used ~ 20 times in 17 files
- [ ] ds-flex + ds-flex-item: used ~ 127 times in 31 files
- [ ] ds-grid + ds-grid-item: used ~ 9 times in 5 files
- [ ] ds-modal: used ~ 4 times in 4 files
- [x] ds-page: not used
- [x] ds-page-title: not used
- [ ] ds-placeholder: used ~ 2 times in 2 files
- [ ] ds-section: used ~ 6 times in 6 files
- [ ] ds-space: used ~ 112 times in 43 files
- [ ] ds-spinner: used ~ 4 times in 3 files

### Typography Components
- [x] ds-chip: not used
- [x] ds-code: not used
- [ ] ds-heading: used ~ 20 times in 18 files
- [ ] ds-icon: used ~ 33 times in 21 files
- [ ] ds-logo: used ~ 2 times in 2 files
- [ ] ds-tag: used ~ 4 times in 4 files
- [ ] ds-text: used ~ 66 times in 18 files

### Data Input Components
- [ ] ds-form: used ~ 14 times in 14 files
- [ ] ds-input: used ~ 39 times in 18 files
- [ ] ds-radio: used ~ 2 times in 2 files
- [ ] ds-select: used ~ 7 times in 6 files

### Data Display Components
- [ ] ds-avatar: used ~ 2 times in 2 files
- [x] ds-copy-field: not used
- [ ] ds-list + ds-list-item: used ~ 10 times in 3 files
- [ ] ds-number: used ~ 15 times in 3 files
- [ ] ds-table: used ~ 5 times in 5 files
- [ ] ds-button: used ~ 58 times in 43 files
- [ ] ds-menu: used ~ 8 times in 7 files

**Comment by Mogge** [comment]
not stale
