### ISSUE TITLE
🚀 [Feature] Viewing modes

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#2872]
## :rocket: Feature

Users should be able to change the viewing mode:
- [ ] Tiles
- [ ] Cockpit
- [ ] Map
- [ ] Hybrid

...as shown in the video [ClickDummy 05 - Ansichtsmodi](https://tube.tchncs.de/videos/watch/87439e60-c6b1-402f-8fc5-f292c16fc33c).

### User Problem

So long, cluttered tiles view! Users benefit from spending their time more efficienctly on the network, increasing satisfaction, happiness and the motivation to donate. 
HC benefits from reaching its mission because users can more efficiently engage for peace and create social change.

### Implementation

- [ ] Add a bar to the header that contains the sorting menu and the viewing mode selection menu.
On the selection menu add:
- [ ] the 'Tiles' view
- [ ] the 'Cockpit' view
- [ ] the 'Maps' view
- [ ] the 'Hybrid' view

The details of each view need to be defined.

### Design & Layout

The layout is probably like in the video, details to be defined.
