### ISSUE TITLE
Editor Improvements

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#289]
Improve the Editor usage (sequel of https://github.com/Human-Connection/Nitro-Web/pull/153)

**Todo`s:**
- [x] edit posts
- [ ] create posts
  - [x] title
  - [x] content
  - [ ] tags
  - [ ] categories
- [x] fix broken integration test as now you cant report your own contributions or your self as a user
- [x] always add `target="_blank"` to the rendered links
- [ ] render all content with the editor-content component
- [ ] **Stylings**
  - [x] bold
  - [x] italic
  - [ ] strike
- [ ] **Elements**
  - [x] links

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/Human-Connection/Human-Connection/issues/379
