### ISSUE TITLE
🌟 [EPIC] User IDs

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#3007]
## 🌟 EPIC
discussed with @DennisHack 

Users should be able to toggle other users' `IDs` on the network, so they can reliably identify them.

### User Problem
At the moment it is quite easy to pose as someone else on Human Connection. This can lead to confusion and can be exploited. A visible unique `user ID` would help to make sure a user really is the one he says he is – we already have these IDs in the database, so this issue is (mainly) about displaying them on the frontend.

### Implementation Step by Step
- [ ] Make IDs short and readable (this will also help with the design): #2786 
- [x] Remove the `hover menu` from the `user teaser`: #3004
- [ ] Add a `toggle ID` button to the `user teaser`: #3005
- [ ] Add a `toggle ID` button to the `user profile`: #3006

### Additional context
The following issues are related but outdated: #252, #2784
The following PR could be used as a basis for updating the `user profile`: #2884
