### ISSUE TITLE
🌟 [EPIC] Blacklist

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#307]
### Userstory

```gherkin
Feature: Blacklist
  As a user
  I want to managed different blacklists for certain people, tags, categories or terms
  In order to keep me away from content I don't want to see.
```
- [ ] 🚀 [Feature] Build a list of Blacklists
- [ ] 🚀 [Feature] Build the blacklist itself which can be each switched on or off. 

A Blacklist can contain filter for the following four entities:
- [ ] 🚀 [Feature] Blacklist Users #279
- [ ] 🚀 [Feature] Blacklist Categories #1720
- [ ] 🚀 [Feature] Blacklist Tags #1721
- [ ] 🚀 [Feature] Blacklist Terms #1722
- [ ] 🚀 [Feature] Blacklist Content 18+ (although we currently have just adult users) #1723

### Design & Layout

![blacklist](https://user-images.githubusercontent.com/13457963/65607249-80d01400-dfac-11e9-942d-4d1c0291f01f.png)

Video: [HC Blacklist](https://www.youtube.com/watch?v=abkPinpkrh0)

### Additional context

Later blacklists can be shared. 

As blacklists later may be shared, they should be copied over, so that they later can be changed from each user independently, not reference counted.

**Comment by Jensebluemchen** [comment]
On Zoomstag Meeting some People have ideas about Blacklist
When activating the blacklist, ask install. For example, how long should it be 1 day 1 week 1 month, etc.
Or from how many exclamations (shouts) of a contribution of the blocked user it nevertheless to be indicated.

**Comment by Jensebluemchen** [comment]
I do not want to block a USER but limit the maximum number of their contributions!
like this:
From how many exclamations (Shouts) of contributions of a user these are NOT to be displayed but BLOCKED!
LG & thank you Andrea
