### ISSUE TITLE
🔧 [Refactor] Don’t Expose Some Properties Of The Report Node In GraphQL

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#3074]
## :zap: Refactor ticket

In some cases there is the danger that informations of the `Report` node getting exposed to the frontend. Especially the `filed` property.

### Motive

Security.

### Related issues

None.

### Implementation

- Set permissions in `permissionMiddleware`.
- Write tests for it.

### Todo

- [X] set GQL permission (done by #3075 )
- [x] write tests (done by #3075 )
- [x] refactor now failing tests (done by #3075 )
- [ ] database manipulation to set `Report.disable` to the final decision, last review rules

**Comment by mattwr18** [comment]
closing this as we are no longer exposing `Report` properties to unauthorized users. 
The ToDo to write a database migration has been extracted into its own issue. See https://github.com/Human-Connection/Human-Connection/issues/3412
