### ISSUE TITLE
🌟 [Epic] Notifications

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#345]
### Notifications

![image](https://user-images.githubusercontent.com/1238238/55475899-6f1d3d80-5615-11e9-9f41-35aca6e08dc1.png)

- [x] Add mutation to mark a notification as read  https://github.com/human-connection/human-connection/issues/346
- [x] Display notifications in the frontend https://github.com/human-connection/human-connection/issues/347
- [x] Click on notification and mark it as read https://github.com/human-connection/human-connection/issues/348
- [x] ~Send and receive notifications via ActivityPub https://github.com/human-connection/human-connection/issues/349~
- [x] Query currentUser's notifications https://github.com/human-connection/human-connection/issues/350
- [x] Generate a link from @-mention in editor #447

### Userstory
```gherkin
Feature: Notifications for a mentioning
  As a user
  I want to be notified if sb. mentions me in a post or comment
  In order join conversations about or related to me
```

### Design & Layout

![image](https://user-images.githubusercontent.com/1238238/55475492-5f512980-5614-11e9-9892-71ec1f0abab6.png)

![image](https://user-images.githubusercontent.com/1238238/55475472-52ccd100-5614-11e9-8625-208e8607bb9d.png)

**Comment by Tirokk** [comment]
# [Future?] Additional Functionality Suggestion

## User Story

My actual user experience in the old Alpha: An overload of notifications means an overload of work to review them …
If I was not in there for some days or haven’t worked on them.
Because I followed some users which posts a lot, as an example.

```gherkin
Feature: Sort notifications and/or display settings
  As a user
  I want to see first, if somebody has mentioned me personally.
  And later I can have a look what others posted.
```

```gherkin
Feature: Quick and save deletion of notifications
  As a user
  I want to be able to choose or search specific notifications.
  And view or delete them quickly (together) to reduce work overload.
```

**Comment by roschaefer** [comment]
@ulfgebhardt it turned out that https://github.com/Human-Connection/Human-Connection/issues/349 is not required for this Epic. It is not necessary to send a HTTP request to your own server to create a notification, that's handled by a direct access to the database.

Therefore I removed https://github.com/Human-Connection/Human-Connection/issues/349 from the epic and from our current sprint.

@Mastercuber if we federate, the activityPub middleware would have to know somehow if a notification was created and send out http requests in case the actor is a user from a remote server.

**Comment by roschaefer** [comment]
@Tirokk feel free to create Github issues from your user-stories, I'll close this Epic now.
