### ISSUE TITLE
🌟 [EIPC] Post editor improvements

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#3625]
## :rocket: Feature

The post editor #328 and #379 has room for improvement. This issue is to collect issues that improve the post editor.

**Bugs**
- [ ] 🐛 Lists in posts and comments are not displayed as lists #3492 
- [ ] 🐛 Editor toolbar on very long articles works not properly #2171 
- [ ] 🐛 Editor using LegacyEmbed, only #3395 
- [ ] 🐛 No warning when leaving the editor accidentally #1858
- [ ] 🐛 Paste in Editor inserts additional Newlines #1856
- [ ] 🐛 Language select looks disabled – but it's not #1467

**Features**
- [ ] 🚀 Explain Editor Icons with a hover/Mouseover #1950 
- [ ] 🚀 Contributions: Media file upload option #1066 
- [ ] 🚀 I would like to have pictures in the editor #3158 
- [ ] 🚀 [Question] Do we want an image button for the editor? #1472  
- [ ] 🚀 Remove 'Carriage Return' within marked text sections #2920 
- [ ] 🚀 Create the teaser image from the metadata of a pasted link(->embed) #1200 
- [ ] 🚀 Show supported image formats in editor #1949

### User Problem

The post editor is very often used by users. Every improvement to the editor increase efficiency and happiness of the users.

### Implementation

Fix the bugs first. Prioritize feature requests, then start working on it.

### Additional context

As discussed with @Raimundo-dev today.
