### ISSUE TITLE
🌟 [EPIC] User Dashboard / Home

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#372]
### User Dashboard / Home

![image](https://user-images.githubusercontent.com/1238238/55469422-c7e4da00-5605-11e9-93dd-71c0e960a211.png)

Header:
- [X] GoToFeed
- [ ] Search https://github.com/Human-Connection/Human-Connection/issues/308
- [ ] Filter https://github.com/Human-Connection/Human-Connection/issues/374
- [X] Language
- [x] Notifications https://github.com/Human-Connection/Human-Connection/issues/345
- [X] Usermenu
- [ ] Sorting https://github.com/Human-Connection/Human-Connection/issues/375

Post Card:
- [x] Author Bug https://github.com/Human-Connection/Human-Connection/issues/376
- [X] CreatedAt
- [X] Title
- [X] Content Excerpt
- [X] Categories
- [X] Actions
- [x] Design differences https://github.com/Human-Connection/Human-Connection/issues/377
- [ ] Dynamic Card Height https://github.com/Human-Connection/Human-Connection/issues/378

More:
- [ ] New Post https://github.com/Human-Connection/Human-Connection/issues/379 + ~~Bug~~ https://github.com/Human-Connection/Human-Connection/issues/337
- [ ] Footer https://github.com/Human-Connection/Human-Connection/issues/381

### Userstory

```gherkin
Feature: News Feed
  As a user
  I want to see a list of contributions, possibly filtered and sorted,
  In order to get interesting news and ideas and get possibly involved in candos and projects.
```

### Design & Layout - Vision
![image](https://user-images.githubusercontent.com/1238238/55667309-ee4f8300-585a-11e9-945d-ecbdaf47ebca.png)

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55667323-25be2f80-585b-11e9-92f3-2a86cf685b1c.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55472317-18f7cc80-560c-11e9-80cf-962c81383c1b.png)
