### ISSUE TITLE
🚀 [Feature] Filter

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#374]
### Filter
![image](https://user-images.githubusercontent.com/1238238/55473778-c5877d80-560f-11e9-9999-26542d2d4982.png)

- [x] Categories https://github.com/Human-Connection/Human-Connection/issues/967
- [x] Emotions - depends on https://github.com/Human-Connection/Human-Connection/issues/384
- [ ] Group Emoticons in 3 categories [Positive, Other, Netagive]
- [ ] No Filter selected = empty Page
- [ ] Filter for Post Type
- [ ] Default Filter ( Happy )
- [ ] Persisten Filter-Settings per User
- [ ] (optional) Recheck Usability when clicking one icon deselect it (seems not the thing I expect when clicking) Talk to @ulfgebhardt when you implement this
- [ ] (optional) Rethink the Design an pack the Filter in a better way
- [ ] Filter by user type (source): **All** or **connections** (friends), additional to followers

Regarding Emoticons
```
Sort and devide them into 3 categories (Filter): 

POSITIVE: Heart (1), happy (2), funny (3)

OTHER: suprised (4), questioning (5)

NEGATIVE: Broken Heart (Heart broken) (6), cry/sad (7), angry (8), help! (blue siren on head) (9), fear (10) 
```

### Userstory Categories
```
As a network user
I'd like to filter posts by categories
E.g. when I am only interested in political content or not interested in religous content
```

### Userstory Emotions
```
As a user
I'd like to filter posts by emotions
E.g. when I am not in the mood for sad or upsetting content
```

### Design & Layout - Vision

![image](https://user-images.githubusercontent.com/1238238/55667303-bc3e2100-585a-11e9-99c6-285a75ddcd94.png)

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55474056-873e8e00-5610-11e9-8493-9962754d99c5.png)

Click on Sub-Icon - disables (check if thats a good aproach)
![image](https://user-images.githubusercontent.com/1238238/55474079-97566d80-5610-11e9-8755-aed8225ee88d.png)

Click on All-Icon (if all are selected -> all deselected; if not all are selected -> all selected)
![image](https://user-images.githubusercontent.com/1238238/55474137-bd7c0d80-5610-11e9-8502-dd52383b7989.png)
![image](https://user-images.githubusercontent.com/1238238/55667341-65851700-585b-11e9-9d63-dbdf3e3c19c9.png)

### Design & Layout - Nitro

Missing
