### ISSUE TITLE
🚀 [Feature] Create Post

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#379]
### Create Post

![image](https://user-images.githubusercontent.com/1238238/55479189-d17a3c00-561d-11e9-912b-78f4c74936c0.png)

- [x] Teaser Image https://github.com/Human-Connection/Human-Connection/issues/759
- [ ] Delete teaser image #1188
- [ ] Create the teaser image from the metadata of a pasted link(->embed) #1200
- [x] Author (self) + last active https://github.com/Human-Connection/Human-Connection/issues/760
- [ ] Contribution Type Select https://github.com/Human-Connection/Human-Connection/issues/777
- [X] Title
- [X] Content
- [x] Categories of Contribution https://github.com/Human-Connection/Human-Connection/issues/778
- [x] Tags of Contribution https://github.com/Human-Connection/Human-Connection/issues/779
- [x] Language of Contribution https://github.com/Human-Connection/Human-Connection/issues/781
- [ ] Country of Contribution? https://github.com/Human-Connection/Human-Connection/issues/782
- [ ] Visibility (Alpha: everything is visible, so I think not for the release?) https://github.com/Human-Connection/Human-Connection/issues/784
- [ ] Design (we have to see, if the functionality is there)
- [ ] StepByStep Post-Creation (what does that mean, asks @Tirokk )

ContentEditor:
- [X] bold option
- [X] italic option
- [X] link url option
- [ ] strike option
- [x] lists options (order & unordered)
- [x] quote option
- [x] embed option
- [ ] emoticons menu
- [ ] menu for all the Text-Style-Options @appinteractive ?
- [x] render all content with the editor-content component @appinteractive what does this mean?

Bugs:
- [x] Categories are not localised #1201
- [x] Editor link button has no effect #1198
- [x] Editor placeholder and menu overlap #1197
- [x] Post image: preview image differs from final result #1199
- [x] Bug on mobile regarding usability https://github.com/Human-Connection/Human-Connection/issues/285 @appinteractive selecting something on a smartphone is a pain - disable that feature on mobile?

> Menu references this: 
![image](https://user-images.githubusercontent.com/1238238/56281014-d35af980-610b-11e9-86b9-cd9b1fa480f8.png)

CanDo (optional):
- [ ] Difficulty
- [ ] Heading - about/title
- [ ] Content - why

### Userstory
```
Feature: Posts
  As a user
  I want to write posts and see them listed
  In order to share my personal interests and ideas with others.
```

```
Feature: Can do
  As a user 
  I want to create a „Can-Do“, a special type of post which is a tutorial how to have some positive impact 
  in order to encourage other users to make the world a better place
```

### Design & Layout - Vision

![image](https://user-images.githubusercontent.com/1238238/55667641-2e186980-585f-11e9-8eda-817d146c3920.png)

### Design & Layout - Alpha

Post:
![image](https://user-images.githubusercontent.com/1238238/55479424-5b2a0980-561e-11e9-8a2e-7bad2979b102.png)

CanDo:
![image](https://user-images.githubusercontent.com/1238238/55479538-9593a680-561e-11e9-86bb-57b20d54ab7a.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55479275-038b9e00-561e-11e9-91cd-b82acc7ffe5b.png)

![image](https://user-images.githubusercontent.com/1238238/55479340-274ee400-561e-11e9-9516-441eea4dbdae.png)

### Additional context

The new content-create dialog is step by step -> first insert title -> then insert content -> cool? @DennisHack
