### ISSUE TITLE
🌟 [EPIC] Post

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#382]
### Post
![image](https://user-images.githubusercontent.com/1238238/55485052-f4aae880-5629-11e9-83db-fb1e08816146.png)

Create Post:
- [ ] See Feature #379

Post:
- [X] Author
- [X] Post-Date
- [X] Title
- [X] Content
- [X] Categories
- [X] Tags
- [ ] Delete teaser image #1188

Content Menü (dots):
- [X] Report as User
- [X] Deactivate as Admin
- [X] Edit as Author
- [x] (optional) Delete Post as Author https://github.com/Human-Connection/Human-Connection/issues/330

Actions:
- [x] Emotions https://github.com/Human-Connection/Human-Connection/issues/384
- [X] Shouts & Shout Button

Comments https://github.com/Human-Connection/Human-Connection/issues/305: 
- [X] Number of Comments
- [X] Author
- [x] Comment-Date https://github.com/Human-Connection/Human-Connection/issues/305
- [ ] Upvote (Not necessary for migration! May should not be possible on old Alpha Posts!? Ask @Tirokk ) https://github.com/Human-Connection/Human-Connection/issues/305
- [X] Text
- [ ] Reply https://github.com/Human-Connection/Human-Connection/issues/305
- [x] Write Comment https://github.com/Human-Connection/Human-Connection/issues/305

Side Menu:
- [X] Post
- [X] Post - Hide unimplemented Links "Let's Talk" and "Versus" https://github.com/Human-Connection/Human-Connection/issues/386
- [ ] More Info https://github.com/Human-Connection/Human-Connection/issues/393
- [ ] Take Action https://github.com/Human-Connection/Human-Connection/issues/394
- [X] Sticky Menu - always visible https://github.com/Human-Connection/Human-Connection/issues/385
- [x] Scroll on Menu click https://github.com/Human-Connection/Human-Connection/issues/436

Others:
- [X] Design differences https://github.com/Human-Connection/Human-Connection/issues/392
- [ ] Repost a post that your followers and friends can see it #1374

### Userstory
```
Feature: Posts
  As a user
  I want to edit posts
  In order to share my personal interests and ideas with others.
```

### Design & Layout - Alpha

Post with Picture:
![image](https://user-images.githubusercontent.com/1238238/55485194-3d62a180-562a-11e9-98f3-de194526d99b.png)
![image](https://user-images.githubusercontent.com/1238238/55485222-523f3500-562a-11e9-922a-b9abc8298494.png)
![image](https://user-images.githubusercontent.com/1238238/55485249-61be7e00-562a-11e9-9ab3-c2c97537caca.png)

Post with Video embeded:
![image](https://user-images.githubusercontent.com/1238238/55485339-8f0b2c00-562a-11e9-9eec-72144a6f0f79.png)

CanDo Post:
![image](https://user-images.githubusercontent.com/1238238/55485425-b95ce980-562a-11e9-88c4-cc031d0d4e62.png)

### Design & Layout - Nitro

Current Status:
![image](https://user-images.githubusercontent.com/1238238/55485556-f7f2a400-562a-11e9-8168-9d1e946ff3f1.png)
![image](https://user-images.githubusercontent.com/1238238/55485579-0476fc80-562b-11e9-935f-d75c842c0c3e.png)

**Comment by Tirokk** [comment]
# Posts in relation to Countries and Languages

## Question

What do countries and languages mean to the view of my dashboard / home page?

### Purpose

Be able to filter the posts shown on the dashboard / home page by country and language.

### Problem

The dashboard / home page will show all posts of all countries and languages at the moment.
This is not useful in the close future.

### Description

Ascertainments:
- We are a multi country and multi language platform.
- Countries can have multi languages as well.

Because we are a multi country platform:
- I think the author should be able to set the country of a post in the post via menu.
- Default should be the current country of the user.

Because we are a multi language platform:
- I think the author should be able to set the language of a post in the post via menu.
- Default should be the current user language.

### Benefit

- If I filter for an other country as mine, I can get a feeling what is going on there in the sense of Human Connection.
- If I filter for an other language than mine, I can have kind of learning stuff for this language in the sense of Human Connection.
