### ISSUE TITLE
🌟 [EPIC] User Profile

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#395]
### User Profile

![image](https://user-images.githubusercontent.com/1238238/55546954-938a2000-56d0-11e9-8de8-24d30cdb9eaa.png)

- [ ] (optional) Header Image + Upload https://github.com/Human-Connection/Human-Connection/issues/397
- [X] UserImage
- [x] UserImage Upload https://github.com/Human-Connection/Human-Connection/issues/399
- [X] Username
- [X] (optional) Access Settings from Profile as Owner https://github.com/Human-Connection/Human-Connection/issues/400

Contributions:
- [X] Contribution Count
- [X] Comments Count
- [X] Shouts Count

Network:
- [ ] (optional) User follows NGOs Count @appinteractive What is a NGO Database wise - an user, an orga?
- [X] User follows People Count @appinteractive Can we rename "Folgen" into "Followers"? makes sense?
- [ ] (optional) User follows Projects Count @appinteractive What is a Project Database wise - an user, an orga?

(optional) Being Active/CanDos:
- [ ] (optional) CanDo Commitment Count
- [ ] (optional) CanDo Completed Count
- [ ] (optional) List of CanDo's participated in

Posts:
- [ ] (optional) Question "What are your Plans for Today $username?" @appinteractive @dennishack Whats the stance here?
- [X] Create Post Button
- [X] Posts done cronologically

Comments:
- [x] Tab not implemented https://github.com/Human-Connection/Human-Connection/issues/401

Shouts:
- [x] Tab not implemented https://github.com/Human-Connection/Human-Connection/issues/402

### Userstory
```
Feature: User Profile
  As a user
  I want to show personal information to other users in my profile
  In order to tell about me and get in contact with them.
```

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55547043-c502eb80-56d0-11e9-82f0-b2ebfc167fd2.png)
![image](https://user-images.githubusercontent.com/1238238/55547086-dcda6f80-56d0-11e9-8178-c798128ab97e.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55556251-609f5680-56e7-11e9-85bc-31dfc389c8d7.png)
