### ISSUE TITLE
🚀 [Feature] Upload UserProfile Image

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#399]
## 🚀 Feature

**As** a user
**I would like** to be able to add an avatar/profile pic to my profile
**So that** I can personalize my profile

![image](https://user-images.githubusercontent.com/1238238/55557660-9c87eb00-56ea-11e9-92f7-0f078dc6032c.png)

- [ ] Select File Dialog
- [ ] Upload and save Image on Server (persist)
- [ ] Crop Image properly

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55557695-b88b8c80-56ea-11e9-9a5a-73b30573e59d.png)

### Design & Layout - Nitro

Not implemented:
![image](https://user-images.githubusercontent.com/1238238/55562799-f9889e80-56f4-11e9-84a1-5b8384f25449.png)

**Comment by mattwr18** [comment]
A couple questions I have before diving into this.
1) What exactly is meant by `Select File Dialog`? Is this to be interpreted as a `Modal` with some text and the ability to add a file to upload? Currently, on https://alpha.human-connection.org/profile their can click on their profile pic and it directly opens their computer's file explorer, where a pic can be chosen. Drag and drop is also supported.

2) What do people think about reusing the `Upload.vue` component from `/WebApp`, https://github.com/Human-Connection/WebApp/blob/develop/components/Global/Form/Upload/Upload.vue, which has other components https://github.com/Human-Connection/WebApp/blob/develop/components/Global/Elements/ProgressBar/ProgressBar.vue and  https://github.com/Human-Connection/WebApp/blob/develop/components/Global/Elements/ProgressiveImage/ProgressiveImage.vue, as well as a fork of `vue-clip` https://github.com/alexsasharegan/vue-clip.

The fork does not seem to be maintained, so maybe not, but in general is the idea to build everything from scratch?

3) Is this user story I added adequate, or should it be changed in some way?
**As** a user
**I would like** to be able to add an avatar/profile pic to my profile
**So that** I can personalize my profile

4) Is this `UserProfile` image the same as a user's avatar, or different in some way?
5) based on the answer above, will it have a type of it's own.. i.e create a node and have some relationship between `User` and it?

I'm sure there are other questions that will come up, but for now, if someone could help make these decisions, it will potentially save time by not implementing it one way and then changing it completely at the first code review. Thanks :smiley_cat:

**Comment by ulfgebhardt** [comment]
Regarding 1 - This is how the Alpha solved this:
![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/161aed27-07c9-4f48-b7a7-5279d37232b4)
