### ISSUE TITLE
🌟 [EPIC] User Settings

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#403]
### User Settings
![image](https://user-images.githubusercontent.com/1238238/55564571-78cba180-56f8-11e9-92a3-11d3dcecd887.png)

- [X] Header "Settings"
- [ ] Navigation Crumbs "Settings / Subpage" https://github.com/Human-Connection/Human-Connection/issues/405
- [X] Save Settings (on each Page)

Your Data:
- [X] Name
- [x] Name changeable - Bug https://github.com/Human-Connection/Human-Connection/issues/376
- [ ] EMail https://github.com/Human-Connection/Human-Connection/issues/407
- [ ] Avatar https://github.com/Human-Connection/Human-Connection/issues/408

Security:
- [X] Current password
- [x] New Password -> Bug https://github.com/human-connection/human-connection/issues/247
- [X] New Password Repeat
- [x] Password strength https://github.com/Human-Connection/Human-Connection/issues/410

(optional) Invites:
- [ ] Generate invite Code Button
- [ ] Display Invite Codes + Copy Link Button
- [ ] Invite System

(later) Download Data:
- [ ] Send Download Link Button + Functionality https://github.com/Human-Connection/Human-Connection/issues/211

Delete Account https://github.com/Human-Connection/Human-Connection/issues/404:
- [x] Confirm slider https://github.com/Human-Connection/Human-Connection/issues/404
- [x] Delete Button + Functionality https://github.com/Human-Connection/Human-Connection/issues/404

(optional) My Organizations:
- [ ] Create New Orga Button
- [ ] Select existing Orgas -> Profile
- [ ] Delete existing Orga
- [ ] Existing Orga Settings

Languages https://github.com/Human-Connection/Human-Connection/issues/409:
- [ ] Content Languages enable/disable https://github.com/Human-Connection/Human-Connection/issues/409
- [ ] Interface Language https://github.com/Human-Connection/Human-Connection/issues/409

(optional) Presentation:
- [ ] Hide Users slider + Functionality

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55564684-b7f9f280-56f8-11e9-85d1-88200bafbdb7.png)
![image](https://user-images.githubusercontent.com/1238238/55564701-c47e4b00-56f8-11e9-896d-ef1236b2c94a.png)
![image](https://user-images.githubusercontent.com/1238238/55564718-cd6f1c80-56f8-11e9-91d8-670bc4cdb700.png)
![image](https://user-images.githubusercontent.com/1238238/55565374-fe9c1c80-56f9-11e9-941d-c1b64d84d637.png)
![image](https://user-images.githubusercontent.com/1238238/55564734-d7911b00-56f8-11e9-9613-cd0bfc689d9a.png)
![image](https://user-images.githubusercontent.com/1238238/55564750-e1b31980-56f8-11e9-9f94-22305b860fa2.png)
![image](https://user-images.githubusercontent.com/1238238/55564765-ea0b5480-56f8-11e9-9f0a-5637ff2cba3f.png)
![image](https://user-images.githubusercontent.com/1238238/55571603-19748e00-5706-11e9-9cc1-cdae7b7bb802.png)
![image](https://user-images.githubusercontent.com/1238238/55564792-f8597080-56f8-11e9-8d27-2f3749d4e987.png)
![image](https://user-images.githubusercontent.com/1238238/55564815-0909e680-56f9-11e9-8dbd-de618eee1317.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55564845-1626d580-56f9-11e9-8984-c1204550afce.png)
![image](https://user-images.githubusercontent.com/1238238/55564868-2048d400-56f9-11e9-8c05-abb45c5bdb82.png)
![image](https://user-images.githubusercontent.com/1238238/55564905-2c349600-56f9-11e9-96b6-010befc54000.png)
![image](https://user-images.githubusercontent.com/1238238/55564928-35256780-56f9-11e9-9cb3-ab8b52796d12.png)
![image](https://user-images.githubusercontent.com/1238238/55564954-3ce50c00-56f9-11e9-8aaa-e2065a69a517.png)
![image](https://user-images.githubusercontent.com/1238238/55564974-453d4700-56f9-11e9-9ada-a2d5be0df015.png)
![image](https://user-images.githubusercontent.com/1238238/55564988-4d958200-56f9-11e9-8a51-3a7d261d82d6.png)
