### ISSUE TITLE
🌟 [EPIC] Administration

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#412]
### Administration
![image](https://user-images.githubusercontent.com/1238238/55579503-b3ddcd00-5718-11e9-9c95-3f0184cf1c1a.png)

- [ ] Create a pinned Post for administration #1205
- [ ] Dashboard Statistics https://github.com/Human-Connection/Human-Connection/issues/417
- [ ] (optional) Organisations https://github.com/Human-Connection/Human-Connection/issues/418
- [ ] Users https://github.com/Human-Connection/Human-Connection/issues/419
- [ ] (optional) Invites (make own section for this) https://github.com/Human-Connection/Human-Connection/issues/420
- [ ] Pages https://github.com/Human-Connection/Human-Connection/issues/421
- [ ] System Notifications https://github.com/Human-Connection/Human-Connection/issues/422
- [ ] Categories https://github.com/Human-Connection/Human-Connection/issues/423
- [ ] (optional) Settings https://github.com/Human-Connection/Human-Connection/issues/424
- [ ] Pretty and translatable invite and registration E-Mails #1186

### Userstory
```
Feature: Administration
  As an administrator of the network
  I want to be able to perform needed administrative tasks, like deleting users, correcting badges, see network statistics, creating announcements, write informational pages, like privacy statement and terms of service and others,
  In order to keep the network running and inform and help people, which are not able to help themselves.
```

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55579538-c7893380-5718-11e9-8d4c-6e14349d699a.png)
![image](https://user-images.githubusercontent.com/1238238/55579552-cf48d800-5718-11e9-983a-e20d9b782822.png)
![image](https://user-images.githubusercontent.com/1238238/55622706-3f9b3c00-57a1-11e9-959b-b9018625ef52.png)
![image](https://user-images.githubusercontent.com/1238238/55579625-f7383b80-5718-11e9-873c-bd1715c9790e.png)
![image](https://user-images.githubusercontent.com/1238238/55579645-028b6700-5719-11e9-8b36-d641615e75ba.png)
![image](https://user-images.githubusercontent.com/1238238/55580297-901b8680-571a-11e9-9c0d-eda218b97e0e.png)
![image](https://user-images.githubusercontent.com/1238238/55580343-a1649300-571a-11e9-978f-8dc4aa16789d.png)
![image](https://user-images.githubusercontent.com/1238238/55579653-0cad6580-5719-11e9-9638-8884f39aca19.png)
![image](https://user-images.githubusercontent.com/1238238/55579679-1931be00-5719-11e9-9e29-dc62be22d0e9.png)
![image](https://user-images.githubusercontent.com/1238238/55579696-26e74380-5719-11e9-9dc8-5e4dc9c99f0c.png)
![image](https://user-images.githubusercontent.com/1238238/55579722-349cc900-5719-11e9-8819-33a173283426.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55579751-48482f80-5719-11e9-868a-0792ac875806.png)
![image](https://user-images.githubusercontent.com/1238238/55579775-51d19780-5719-11e9-92ff-506e2f003105.png)
![image](https://user-images.githubusercontent.com/1238238/55579787-58f8a580-5719-11e9-91c1-fc8c0967d4ab.png)
![image](https://user-images.githubusercontent.com/1238238/55579797-60b84a00-5719-11e9-93c0-8f7c6a8fc30c.png)
![image](https://user-images.githubusercontent.com/1238238/55579809-6ada4880-5719-11e9-9c27-ff0b83678809.png)
![image](https://user-images.githubusercontent.com/1238238/55579833-76c60a80-5719-11e9-9b57-965e3641c1da.png)
![image](https://user-images.githubusercontent.com/1238238/55579856-804f7280-5719-11e9-863b-2f7a09879a36.png)
![image](https://user-images.githubusercontent.com/1238238/55579868-88a7ad80-5719-11e9-8787-7c2db432f2bd.png)

**Comment by ogerly** [comment]
https://github.com/Human-Connection/Human-Connection/issues/962  this is close from me ... 
#422 is work for this
