### ISSUE TITLE
🌟 [EPIC][Release] Nitro

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#414]
### Migrate Nitro
![image](https://user-images.githubusercontent.com/1238238/55667277-67020f80-585a-11e9-92ee-8e44c82c6fd2.png)

This Epic is just to summarize all Epics of the next Release `Migrate Alpha to Nitro` for easier navigation through them.

- [ ] 🌟 [EPIC] User Dashboard / Home https://github.com/Human-Connection/Human-Connection/issues/372
- [ ] 🌟 [EPIC] Post https://github.com/Human-Connection/Human-Connection/issues/382
- [ ] 🌟 [EPIC] User Profile https://github.com/Human-Connection/Human-Connection/issues/395
- [ ] 🌟 [EPIC] User Settings https://github.com/Human-Connection/Human-Connection/issues/403
- [ ] 🌟 [EPIC] Administration https://github.com/Human-Connection/Human-Connection/issues/412
- [ ] 🌟 [EPIC] Moderation https://github.com/Human-Connection/Human-Connection/issues/425
- [ ] 🌟 [EPIC] Security / Privacy https://github.com/Human-Connection/Human-Connection/issues/426
- [ ] 🌟 [EPIC] DevOps / Other https://github.com/Human-Connection/Human-Connection/issues/427
- [ ] 🐛 [EPIC] Lokalise https://github.com/Human-Connection/Human-Connection/issues/454

Note: This list is incomplete
Note: All coresponding Issues can be found in the Milestone https://github.com/Human-Connection/Human-Connection/milestone/10 + the current Sprint

![image](https://user-images.githubusercontent.com/1238238/55667379-e217f580-585b-11e9-99b5-50e529481276.png)

### More
View Click Dummy Video: https://www.youtube.com/watch?v=rUYjaDVm9Xk
