### ISSUE TITLE
🌟 [EPIC] Moderation

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#425]
### Moderation
![image](https://user-images.githubusercontent.com/1238238/55630878-0cfc3e00-57b7-11e9-96d5-6f816a5d4a5e.png)

- [X] List of Reported Users, Posts & Comments
- [x] Reenable Post once it has been disabled https://github.com/Human-Connection/Human-Connection/issues/432
- [X] [Bug] Disabled Posts - Border is rendered over Profile-Menu https://github.com/Human-Connection/Human-Connection/issues/433
- [x] 🚀 [Feature] [Moderation] When reporting Content Users can add specific information #1707
- [x] 🚀 [Feature] [Moderation] See reportet Content with additional information #1708 
- [x] 🚀 [Feature] [Moderation] Protocol and list Moderation Decisions #1710
- [x] 🚀 [Feature] Notifications page with all notifications #1974
- [ ] 🚀 [Feature] [Moderation] Send Feedback to reporting User #1709
- [x] 🚀 [Feature] [Moderation] Enforce the moderators to first report before they can disable #1830
- [ ] 🚀 [Feature] Moderator Decision Shall Have Reason And Information #2885
- [ ] 🚀 [Feature] Notify Authors And Users About Decisions #2886
- [ ] Follow Report and ban/block/timeout use

### Advanced

Since the responsibility for moderation should go to the community in order to make the whole Network crowdmoderated.

The currently planned Moderation is centralized.

An Idea of migration is to recruit those who decide like the central moderators into the moderation rank. To get competent Moderations with the start of the Network.

- [ ] There should be a detailed plan made how to make the transition and ticketed
- [ ] There need to be Moderator Recruitment mechanics
- [ ] There need to be a exam for new Moderators before they can do their duties

>  Man wird Beiträge melden können und sie erscheinen bei uns auf dem Moderationsboard 
> Daniel Gast in gelernter Community Manager und war ja für FB tätig 
> er muss die Sachen demnach dann prüfen 
> und jetzt ist es doch eine tolle Sache, wenn diejenigen, die Beiträge melden und z.B. 8/10 Verstöße auch richtige Meldungen sind, in unsere Moderatorenacademy einladen!  
> Quasi mit dem MVP eine gute Vorauswahl haben! 

### Userstory
```
Feature: Moderation
  As a moderator
  I want to be able to get informed about contributions reported by other users
  In order to moderate and see, if the contributions conform with the network's terms of service and law.
```

### Design & Layout

![image](https://user-images.githubusercontent.com/1238238/55630927-28ffdf80-57b7-11e9-8b9a-70b16c53a27e.png)

### Additional context
This is addressing one central point: The right distribution.

- How do we prevent filterbubbles if the right structure is pyramidal?
- Can we decentralize the right distribution?

Consider this: The only privilege an admin should have is the right to shut the whole thing down.

**Comment by Tirokk** [comment]
Is not stale
