### ISSUE TITLE
🌟 [EPIC] Security / Privacy

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#426]
### Security / Privacy

- [x] [Bug] Don't expose private RSA key https://github.com/Human-Connection/Human-Connection/issues/411
- [ ] Checklist ExpressJS Security Best Practices https://github.com/human-connection/human-connection/issues/203
- [ ] Sanitize Input to prevent Injection https://github.com/human-connection/human-connection/issues/204
- [x] Multiple user login https://github.com/human-connection/human-connection/issues/208
- [x] 🐛 Whitelist all auto-generated Mutations/Queries https://github.com/human-connection/human-connection/issues/343

### Additional context

Rised Questions:
- Are the automatically generated mutations a security risk? ( @Tirokk )
  - They are not handled yet by the permissions middleware.
  - Should we whitelist the mutations in general which are handled by the permissions middleware? So all other mutations, not checked for security, are automatically blacklisted …
