### ISSUE TITLE
🌟 [EPIC] DevOps / Other

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#427]
### Neo4J

- [x] Neo4J DB initialization24 https://github.com/Human-Connection/Human-Connection/issues/206
- [ ] 🚀 Automatic import of production data on deployments https://github.com/Human-Connection/Human-Connection/issues/641
- [x] 🚀 [Feature] Backup https://github.com/Human-Connection/Human-Connection/issues/340
- [x] [WIP] Propose a hack to fix performance https://github.com/Human-Connection/Human-Connection/issues/563
- [x] [WIP] Trigger build with modified `neo4j-graphql-js` https://github.com/Human-Connection/Human-Connection/issues/635
- [X] Restore Neo4J backup to Kubernetes cluster https://github.com/Human-Connection/Human-Connection/issues/353

### Kubernetes

- [x] More descriptive minikube setup instructions https://github.com/Human-Connection/Human-Connection/issues/585
- [X] Kubernetes Cronjob to backup Neo4J https://github.com/Human-Connection/Human-Connection/issues/354
- [X] Docs 354 kubernetes cron job for backups https://github.com/Human-Connection/Human-Connection/issues/573
- [X] Fix wrong screenshot in kubernetes docs https://github.com/Human-Connection/Human-Connection/issues/616

### Testing

- [ ] 🚀 Add baseURL to cypress configuration https://github.com/Human-Connection/Human-Connection/issues/576
- [x] 🐛 Re-enable cypress --record on May 2019 https://github.com/Human-Connection/Human-Connection/issues/470
- [X] Setup Test Coverage monitoring https://github.com/Human-Connection/Human-Connection/issues/294
- [X] 🚀 Add testing coverage https://github.com/Human-Connection/Human-Connection/issues/469
- [X] 2019/kw19/codecov https://github.com/Human-Connection/Human-Connection/issues/574

### Alpha

- [ ] Increase Memory for Alpha Rancher https://github.com/Human-Connection/Human-Connection/issues/161

### Documentation 

- [x] 🐛 [Doc] Modify Documentation for use with Monorepo https://github.com/Human-Connection/Human-Connection/issues/479

### Other 

- [ ] 🐛 [Webapp] Lokalise unlocalised texts https://github.com/Human-Connection/Human-Connection/issues/451
- [ ] 🐛 Model for Contributions is not consistent https://github.com/Human-Connection/Human-Connection/issues/623
- [x] 🚀 [Feature] Provide vscode config with lint settings in align with the project settings https://github.com/Human-Connection/Human-Connection/issues/590
- [x] Add thumbor service https://github.com/Human-Connection/Human-Connection/issues/624
- [X] 💬 Hide all unfunctional content till its implemented https://github.com/Human-Connection/Human-Connection/issues/429
- [X] Write component tests for CommentForm.vue https://github.com/Human-Connection/Human-Connection/issues/556
- [X] dummy commit - DO NOT MERGE THIS PR! https://github.com/Human-Connection/Human-Connection/issues/578
- [X] Refactoring validation middleware https://github.com/Human-Connection/Human-Connection/issues/596
- [X] 🍰 2019/kw20/fix_lint_rules_and_vscode https://github.com/Human-Connection/Human-Connection/issues/625

### Frontend

- [X] [Vue warn]: Invalid prop: custom validator check failed for prop "size" https://github.com/Human-Connection/Human-Connection/issues/586
- [X] 296 image component https://github.com/Human-Connection/Human-Connection/issues/499
- [X] Revert tiptap upgrade https://github.com/Human-Connection/Human-Connection/issues/575
- [X] Tiptap bug for 1.8.05 https://github.com/Human-Connection/Human-Connection/issues/572
- [X] Update ds-avatar size to use small https://github.com/Human-Connection/Human-Connection/issues/587
- [X] Revert logout.vue https://github.com/Human-Connection/Human-Connection/issues/594

### Backend

- [X] Refactoring: Prefix URLs pointing to the backend https://github.com/Human-Connection/Human-Connection/issues/296
