### ISSUE TITLE
🌟 [EPIC] Roadmap

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#918]
## 🌟 Roadmap

![image](https://user-images.githubusercontent.com/1238238/60178666-5ee3bb80-981c-11e9-865b-c37f8e7c3a8d.png)

### Organisation
- [ ] Human Rights - The UN Charter of Human Rights is the basis of our actions (how is that refelected in the software? e.g. Moderation principal)
- [x] Charitable - Human Connection is recognized and registered as a nonprofit
- [x] Open Source - The code is published for co-programming
- [x] No Data Selling - This is our guarantee to you
- [x] No Advertising - There is no influence due to advertisements or commercial profiles
- [x] Server Location Germany - The platform is subject to strict German data protection laws
- [ ] Crowd Moderated - The wisdom o many is better than the wisdom of a few single moderators https://github.com/Human-Connection/Human-Connection/issues/425
- [ ] Solution-oriented - Human Connection trough Human Connection!
- [ ] Transparency - We are and will be transparent in every respect
- [ ] App Interfaces - Dock with your nonprofit app or database

### Social Network
- [ ] Private Messaging - Private stays private. But don't forget: The NSA also remains the NSA... https://github.com/Human-Connection/Human-Connection/issues/321
- [ ] Chat Rooms - This is where the community meets. https://github.com/Human-Connection/Human-Connection/issues/321
- [ ] Comments & Let's Talk - Why comment if you can talk to each other? https://github.com/Human-Connection/Human-Connection/issues/305 https://github.com/Human-Connection/Human-Connection/issues/322
- [ ] Posts - Share your knowledge with friends or with the whole world. You choose. https://github.com/Human-Connection/Human-Connection/issues/382
- [ ] Blacklist - Hide topics, content and users that annoy you. https://github.com/Human-Connection/Human-Connection/issues/307
- [ ] Digital Gifts - Expressing gratitude is beautiful
- [ ] Meet Me - Meet people from all over the world - offline and online
- [ ] Help Me - Let other users explain the network to you

### Knowledge Network
- [ ] Best List - We let the crowd determine what's best. https://github.com/Human-Connection/Human-Connection/issues/315
- [ ] Pro & Contra - Constructive discussions are possible https://github.com/Human-Connection/Human-Connection/issues/430
- [ ] Voting - Do we want to save the world with Human Connection? Yes! https://github.com/Human-Connection/Human-Connection/issues/723
- [ ] Versus - The knowledge "boxing ring" for factual discussions https://github.com/Human-Connection/Human-Connection/issues/310
- [ ] Overview - Discover the world with 16 subject categories
- [ ] Filter & Sorting - Filter and sort everything even according to your mood
- [ ] Professional Search - For those who want to know exactly. Welcome to the matrix.
- [ ] Cockpit - Newsfeed, cockpit and map provide endless freedom.
- [ ] Crowd News - A "Megaphone" instead of a "Like". What is really important? Shout it out!
- [ ] Network Statistics - Take a look at the Human Connection engine.
- [ ] Professional Editor - May we make it look a bit nicer?
- [ ] Free of Censorship - Conspiracy theories? Pick them apart here!

### Action Network
- [ ] For Organizations - The best thing that can happen to a charitable organization.
- [ ] Action Button - Stop the frustration - make something positive!
- [ ] Can Do - Many small steps make a huge leap.
- [ ] Projects - The world's first social project management tool integrated in public social media.
- [ ] Volunteering - Find the team for your plans.
- [ ] Map Function - Turn off your computer, go outside and take action in your local community.
- [ ] Event Calendar - Don't miss the opportunity to be the change.

### Other
- [ ] Integration into the Fediverse @roschaefer 

### Clickdummys
- [Clickdummy](https://preview.uxpin.com/24a2ab8adcd84f9a763d87ed27251351225e0ecd#/pages/99768901/simulate/sitemap?mode=i)
- [Clickdummy2](http://hc.buldakoff.com/)

### Releases
- [X] Work [done](https://github.com/Human-Connection/Human-Connection/milestones?state=closed)
- [ ] Nitro - [Issue](https://github.com/Human-Connection/Human-Connection/issues/414)&[Milestone](https://github.com/Human-Connection/Human-Connection/milestone/10)
- [ ] Nitro Plus - [Issue](https://github.com/Human-Connection/Human-Connection/issues/494)&[Milestone](https://github.com/Human-Connection/Human-Connection/milestone/16)
- [ ] Nitro Public - [Milestone](https://github.com/Human-Connection/Human-Connection/milestone/11)
- [ ] Ideas - [Milestone](https://github.com/Human-Connection/Human-Connection/milestone/12)
